modLoader="javafml"
loaderVersion="[39,)"
license="MIT License https://github.com/McJtyMods/McJtyLib/blob/1.18/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/McJtyLib/issues"
displayURL="http://github.com/McJtyMods/McJtyLib/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="mcjtylib"
version="${file.jarVersion}"
displayName="McJtyLib"
#updateJSONURL="http://myurl.me/" #optional
description='''
Base mod for all McJty mods
'''
[[dependencies.mcjtylib]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"
    ordering="NONE"
    side="BOTH"
